# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 328eead8223a907a23904d25348a7706e75be9a2415501c09b69ee764c6b5fbe7488ff8a05e3518a7529fbc087d0f6c90ceefd553a79f4693b0e5a6a0446da70

test:
  secret_key_base: 325db4f1ab44bc1197b7fb42a049dfbff35469da24b3136cbc8e7445ccc838463c80f5a1f5c1f69e8fc1d6d43f8c044a684c51d0a51e4b7d51c0a2eeab472e89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
